#!/bin/bash

# Script to clean up all output files generated by run_all_solvers.sh
# Usage: ./cleanup_all_solver_outputs.sh

# Define workspace root
WORKSPACE_ROOT="/home/users/arhandoyaroglu/suOPT"

# Output directory to clean
OUTPUT_DIR="$WORKSPACE_ROOT/results_all_solvers"

# Check if output directory exists
if [ ! -d "$OUTPUT_DIR" ]; then
  echo "Output directory $OUTPUT_DIR does not exist. Nothing to clean."
  exit 0
fi

# Ask for confirmation before deleting
echo "This will delete all solver outputs in: $OUTPUT_DIR"
read -p "Are you sure you want to continue? (y/n): " confirm

if [[ $confirm != [yY] && $confirm != [yY][eE][sS] ]]; then
  echo "Operation cancelled."
  exit 0
fi

# Remove all subfolders and files
echo "Removing Concorde outputs..."
rm -rf "$OUTPUT_DIR/concorde"

echo "Removing LKH outputs..."
rm -rf "$OUTPUT_DIR/lkh"

echo "Removing GPU ACS outputs..."
rm -rf "$OUTPUT_DIR/gpuacs"

echo "Removing PIHC outputs..."
rm -rf "$OUTPUT_DIR/pihc"

# Remove summary files
echo "Removing summary files..."
rm -f "$OUTPUT_DIR/results_summary.txt"
rm -f "$OUTPUT_DIR/summary_report.txt"

# Remove any other files in the output directory
echo "Cleaning up remaining files..."
rm -f "$OUTPUT_DIR"/*.txt
rm -f "$OUTPUT_DIR"/*.log
rm -f "$OUTPUT_DIR"/*.json
rm -f "$OUTPUT_DIR"/*.js
rm -f "$OUTPUT_DIR"/*.sol
rm -f "$OUTPUT_DIR"/*.tour

# Check if directory is empty and remove it if it is
if [ -z "$(ls -A "$OUTPUT_DIR")" ]; then
  echo "Removing empty output directory..."
  rmdir "$OUTPUT_DIR"
fi

# Clean up any temporary files that might have been left in the workspace root
echo "Cleaning up any temporary files in workspace root..."
cd "$WORKSPACE_ROOT"
rm -f *.pul *.sav *.res *.ext *.dat *.mas *.sol
rm -f *.tour *.log *.par

echo "Cleanup completed successfully."
echo "All solver outputs have been removed." 